from pathlib import Path

from docx import Document

from scripts.submission_metadata import (
    docx_metadata_violations,
    pdf_metadata_violations,
    sanitize_docx_metadata,
)


def test_sanitizer_removes_author_tool_dates_and_local_paths(tmp_path: Path):
    path = tmp_path / "private.docx"
    document = Document()
    document.add_paragraph("Visible manuscript content remains.")
    document.core_properties.author = "private-user"
    document.core_properties.last_modified_by = "private-editor"
    document.core_properties.comments = "generated by python-docx"
    document.save(path)

    sanitize_docx_metadata(path)

    assert docx_metadata_violations(path) == []
    reopened = Document(path)
    assert reopened.paragraphs[0].text == "Visible manuscript content remains."


def test_pdf_audit_rejects_tool_and_timestamp_metadata(tmp_path: Path):
    unsafe = tmp_path / "unsafe.pdf"
    unsafe.write_bytes(
        b"%PDF-1.4\n1 0 obj << /Creator (python-docx) "
        b"/CreationDate (D:20260828120000+08'00') >> endobj\n%%EOF\n"
    )
    assert pdf_metadata_violations(unsafe)


def test_pdf_audit_accepts_empty_identity_and_tool_fields(tmp_path: Path):
    clean = tmp_path / "clean.pdf"
    clean.write_bytes(b"%PDF-1.4\n1 0 obj << /Creator () /Producer () >> endobj\n%%EOF\n")
    assert pdf_metadata_violations(clean) == []
